# Generated by Django 3.2.9 on 2021-11-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp']},
        ),
    ]
